### ISSUE TITLE
create a script for to generate the checksum

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/station-store#19]
**Context**
as a dev when I want to list my plugin on the plugin store of massa station, I have to generate checksum of my plugin based on the content of the artifacts  and I will be able to do it automatically using this script. 

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*
the dev has to :
- fill the plugins.json with the right informations, he can skip the checksum fields
- run a script to generate & write the appropriate checksums

**How to**
write a script to generate the checksum of the plugin's artifacts 

**Technical details**
the functions to calculate the checksums are defined in the test
**QA testing**
Update a plugin with the script & create a pr.
run `npm write-checksum massa-wallet` or / and `npm write-checksum --all`
run `npm run test`

**Comment by Thykof** [comment]
QA: I used that script it works well
