### ISSUE TITLE
automate the validation of the PR 

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/station-store#2]
## Context

Check if the submitted plugin follows the current standard 

## User flow

run some unit tests in the CI that runs for each push, the pr will be accepted only if the runs succed

## How to

- create a unit testing file that checks if the json fullfill all the requirements
- call it in the CI

## Technical details

I will be using python with pytest and unittest

**Comment by Pierregvx** [comment]
blocked by https://github.com/massalabs/thyra/issues/609 while we define the standard

**Comment by SlnPons** [comment]
@Pierregvx Is this blocked or in progress please?
