### ISSUE TITLE
Update the store with the new standard & add the new version of the node manager

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/station-store#4]
**Context**
This issue is part of Thyra plan for the mainnet as Milestone 1 to build a robust plugin manager. 
We're updating the standard of the store.

**User flow**
n/a

**How to**
- [x] #7
- [x] #2 
- [x] #6

**Technical details**
n/a
**QA testing**
TBD

**Comment by 0xMazout** [comment]
I think we have two miss in this issue, and it don't imply any responsability

a) We will need in the store a field with the type of version , is it a mandatory version or an optionnal as we discussed here : 


![Image](https://user-images.githubusercontent.com/10938862/233563799-4a03b449-6ad0-407e-8015-623a191fbaaa.png)


b) We will need a field with an ExitMessage (named consequences 👻 ), To display when the user click on shutdown the plugin


![Image](https://user-images.githubusercontent.com/10938862/233564101-128338ab-b4ef-4896-bba7-7ac631607e62.png)


I Think the good way to do this is just to add an issue to add this "Fields for the future milestone" of the plugin manager directly in this issue

@Pierregvx @SlnPons What do you think ? :)

**Comment by SlnPons** [comment]
After discussing together and with other team members, here is the conclusion: 

* About the update options: the suggested solution is not satisfying from a user point of view. So we won't implement optional update for now. AKA all updates will be mandatory.
* For the exit message: this won't be handle by the manifest but by the API and the delete endpoint. So this is not needed in this ticket :) @Pierregvx let's catch up together about this later on when we review this endpoint!

**Comment by SlnPons** [comment]
Blocked by task mentioned in the issue that are both in CR
